In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix

In [2]:
# 1. Load and Preprocess Data
df = pd.read_csv('Online Retail.csv', encoding='ISO-8859-1')

In [3]:
# Step 3: Basic Dataset Overview
print("Shape of dataset:", df.shape)
print("\nFirst 5 rows of data:")
display(df.head())

Shape of dataset: (37005, 8)

First 5 rows of data:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6.0,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [4]:
# Step 4: Dataset Information
print("\nDataset Info:")
df.info()

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37005 entries, 0 to 37004
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    37005 non-null  object
 1   StockCode    37004 non-null  object
 2   Description  36887 non-null  object
 3   Quantity     37004 non-null  float64
 4   InvoiceDate  37004 non-null  object
 5   UnitPrice    37004 non-null  float64
 6   CustomerID   24364 non-null  float64
 7   Country      37004 non-null  object
dtypes: float64(3), object(5)
memory usage: 2.3+ MB

In [5]:
# Step 5: Summary Statistics
print("\nSummary Statistics:")
display(df.describe(include='all'))

Summary Statistics:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,37005,37004,36887,37004.000000,37004,37004.000000,24364.000000,37004
unique,1772,2743,2686,NaN,1537,NaN,NaN,23
top,537434,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,06-12-2010 16:57,NaN,NaN,United Kingdom
freq,675,209,213,NaN,675,NaN,NaN,35114
mean,NaN,NaN,NaN,8.059156,NaN,6.228784,15541.009769,NaN
std,NaN,NaN,NaN,61.664063,NaN,149.270176,1730.504495,NaN
min,NaN,NaN,NaN,-9360.000000,NaN,0.000000,12347.000000,NaN
25%,NaN,NaN,NaN,1.000000,NaN,1.280000,14210.000000,NaN
50%,NaN,NaN,NaN,2.000000,NaN,2.510000,15570.000000,NaN
75%,NaN,NaN,NaN,7.250000,NaN,4.250000,17158.000000,NaN
max,NaN,NaN,NaN,2880.000000,NaN,13541.330000,18269.000000,NaN

In [6]:
# Step 6: Check for Duplicates
duplicates = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicates}")

Number of duplicate rows: 471

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
# Step 7: Check for Missing Values
print("\nMissing Values:")
display(df.isnull().sum())

Missing Values:

InvoiceNo          0
StockCode          1
Description      118
Quantity           1
InvoiceDate        1
UnitPrice          1
CustomerID     12639
Country            1
dtype: int64

In [9]:
df.fillna(0, inplace=True)

In [10]:
# Verify that missing values have been handled
print("\nMissing Values after fillna:")
display(df.isnull().sum())

Missing Values after fillna:

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [11]:
# Drop missing customer IDs and remove negative quantities
df = df.dropna(subset=['CustomerID'])
df = df[df['Quantity'] > 0]

In [12]:
#Use a subset for speed during testing
# df = df[df['Country'] == 'United Kingdom']

# Create the user-item matrix
basket = df.pivot_table(index='CustomerID', columns='Description', values='Quantity', aggfunc='sum').fillna(0)

In [13]:
# Convert to sparse matrix for performance
user_sparse = csr_matrix(basket.values)
item_sparse = csr_matrix(basket.T.values)

In [14]:
# 2. User-User Collaborative Filtering
# ----------------------------------------------
user_similarity = cosine_similarity(user_sparse)
user_sim_df = pd.DataFrame(user_similarity, index=basket.index, columns=basket.index)

def recommend_user_based(user_id, n=5):
    if user_id not in user_sim_df:
        return "User not found."
    similar_users = user_sim_df[user_id].sort_values(ascending=False)[1:n+1]
    recommended_items = basket.loc[similar_users.index].mean().sort_values(ascending=False).head(n)
    return recommended_items

In [15]:
# 3. Item-Item Collaborative Filtering
# ----------------------------------------------
item_similarity = cosine_similarity(item_sparse)
item_sim_df = pd.DataFrame(item_similarity, index=basket.columns, columns=basket.columns)

def recommend_item_based(item_name, n=5):
    if item_name not in item_sim_df:
        return "Item not found."
    similar_items = item_sim_df[item_name].sort_values(ascending=False)[1:n+1]
    return similar_items

In [16]:
def recommend_user_based(user_id, n=5):
    if user_id not in user_sim_df.index: # Check if user_id is in the DataFrame index
        return "User not found."
    # Use iloc for position-based slicing to get the top n similar users (excluding self)
    similar_users = user_sim_df[user_id].sort_values(ascending=False).iloc[1:n+1]
    # The rest of the logic remains the same
    recommended_items = basket.loc[similar_users.index].mean().sort_values(ascending=False).head(n)
    return recommended_items

print("\n--- User-Based Recommendations for Customer 17850 ---")
# The customer ID in the original data is an integer, but after dropna,
# the index of the basket DataFrame becomes a float.
# So, pass the customer ID as a float to match the index type.
print(recommend_user_based(17850.0))

print("\n--- Item-Based Recommendations for 'HAND WARMER RED POLKA DOT' ---")
print(recommend_item_based('HAND WARMER RED POLKA DOT'))

--- User-Based Recommendations for Customer 17850 ---
Description
WHITE HANGING HEART T-LIGHT HOLDER    34.4
WOODEN PICTURE FRAME WHITE FINISH     10.8
WOODEN FRAME ANTIQUE WHITE             9.6
HOMEMADE JAM SCENTED CANDLES           7.2
GREY HEART HOT WATER BOTTLE            7.2
dtype: float64

--- Item-Based Recommendations for 'HAND WARMER RED POLKA DOT' ---
Description
GLASS STAR FROSTED T-LIGHT HOLDER    0.960953
WHITE METAL LANTERN                  0.950959
IVORY EMBROIDERED QUILT              0.945996
VINTAGE BILLBOARD DRINK ME MUG       0.894526
CREAM CUPID HEARTS COAT HANGER       0.889628
Name: HAND WARMER RED POLKA DOT, dtype: float64

In [17]:
pip install mlxtend pandas openpyxl

Requirement already satisfied: mlxtend in /usr/local/lib/python3.11/dist-packages (0.23.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/dist-packages (3.1.5)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.2.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, fpgrowth, association_rules
from mlxtend.preprocessing import TransactionEncoder

In [3]:
df = pd.read_csv('Online Retail.csv', encoding='ISO-8859-1')

In [4]:
df = df[df['Quantity'] > 0]

In [5]:
# 2. Group by transactions
basket = df.groupby(['InvoiceNo'])['Description'].apply(list).values.tolist()

In [6]:
df['Description'] = df['Description'].astype(str)
basket = df.groupby(['InvoiceNo'])['Description'].apply(list).values.tolist()

In [7]:
# 3. Encode transactions
te = TransactionEncoder()
# Now, fit_transform should work as all items in 'basket' are strings
basket_matrix = te.fit_transform(basket)
basket_df = pd.DataFrame(basket_matrix, columns=te.columns_)

In [9]:
# 4. Apriori Algorithm

frequent_apriori = apriori(basket_df, min_support=0.01, use_colnames=True)
rules_apriori = association_rules(frequent_apriori, metric="lift", min_threshold=1.0)

In [8]:
# 5. FP-Growth Algorithm

frequent_fp = fpgrowth(basket_df, min_support=0.01, use_colnames=True)
rules_fp = association_rules(frequent_fp, metric="lift", min_threshold=1.0)

In [10]:
# 6. View Rules

print("\n--- Apriori Rules (Top 5) ---")
print(rules_apriori[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head())

print("\n--- FP-Growth Rules (Top 5) ---")
print(rules_fp[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head())

--- Apriori Rules (Top 5) ---
                         antecedents                        consequents  \
0           (6 RIBBONS RUSTIC CHARM)           (JAM MAKING SET PRINTED)
1           (JAM MAKING SET PRINTED)           (6 RIBBONS RUSTIC CHARM)
2           (6 RIBBONS RUSTIC CHARM)  (PACK OF 72 RETROSPOT CAKE CASES)
3  (PACK OF 72 RETROSPOT CAKE CASES)           (6 RIBBONS RUSTIC CHARM)
4           (6 RIBBONS RUSTIC CHARM)                    (PARTY BUNTING)

    support  confidence      lift
0  0.010352    0.225694  3.690457
1  0.010352    0.169271  3.690457
2  0.012502    0.272569  3.867714
3  0.012502    0.177401  3.867714
4  0.011945    0.260417  2.552937

--- FP-Growth Rules (Top 5) ---
                            antecedents                           consequents  \
0       (ASSORTED COLOUR BIRD ORNAMENT)  (WHITE HANGING HEART T-LIGHT HOLDER)
1  (WHITE HANGING HEART T-LIGHT HOLDER)       (ASSORTED COLOUR BIRD ORNAMENT)
2       (ASSORTED COLOUR BIRD ORNAMENT)            (REGENCY CAKESTAND 3 TIER)
3            (REGENCY CAKESTAND 3 TIER)       (ASSORTED COLOUR BIRD ORNAMENT)
4       (ASSORTED COLOUR BIRD ORNAMENT)                       (PARTY BUNTING)

    support  confidence      lift
0  0.018872    0.263920  2.134131
1  0.018872    0.152608  2.134131
2  0.015448    0.216036  1.975947
3  0.015448    0.141296  1.975947
4  0.014174    0.198218  1.943189